name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    # Set up Maven
    - name: Set up Maven
      uses: s4u/maven-settings-action@v2
      with:
        maven-version: 3.8.5  # You can specify the required Maven version here

    # Build and package the project using Maven
    - name: Build with Maven
      run: mvn clean package

    # Deploy the WAR file to Tomcat
    - name: Deploy to Tomcat
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.http://localhost:9090/ }}
        username: ${{ secrets.admin }}
        password: ${{ secrets.admin }}
        script: |
          rm -rf /path/to/tomcat/webapps/your-app
          cp target/*.war /path/to/tomcat/webapps/
          systemctl restart tomcat9  # Ensure correct restart command
